#! /bin/sh
#
# Scans src/token_enum.h and creates token_names.h
#
# $Id: make_token_names.sh,v 1.4 2006/01/03 00:44:29 bengardner Exp $
#

outfile="src/token_names.h"
names=$(grep "CT_" src/token_enum.h | sed -e 's/,.*//g')

# do a little trick to prevent CVS from expanding the id tag
idstr="Id: $"

cat > $outfile <<EOF
/*
 * Generated by $(basename $0) on $(date) 
 * \$$idstr
 */
 
#ifndef TOKEN_NAMES_H_INCLUDED
#define TOKEN_NAMES_H_INCLUDED

const char *token_names[] =
{
EOF

for item in $names ; do
    name=$(echo $item | sed -e 's/CT_//g')
    echo "   [$item] = \"$name\"," >> $outfile
done

cat >> $outfile <<EOF
};

#endif  /* TOKEN_NAMES_H_INCLUDED */

EOF

