#! /usr/bin/env python
# make_token_names.py
#
# Scans src/token_enum.h and creates src/token_names.h
#

import os
import re

infile = "../src/token_enum.h"
outfile = "../src/token_names.h"

basepath = os.path.dirname(__file__)

header = """/*
 * Generated by `%s`
 */
#ifndef TOKEN_NAMES_H_INCLUDED
#define TOKEN_NAMES_H_INCLUDED

const char *token_names[] =
{
""" % os.path.basename(__file__)

footer = """};

#endif /* TOKEN_NAMES_H_INCLUDED */
"""

with open(os.path.join(basepath, infile), 'r') as h:
    lines = h.read().splitlines()

output = []
# Replace CT_ enum entries as a quoted C string
for line in lines:
    quote = re.sub(r'CT_([^,]*),.*', r'"\1",', line)
    if quote != line:
        output.append(quote + '\n')

with open(os.path.join(basepath, outfile), 'w') as h:
    h.write(header)
    h.writelines(output)
    h.write(footer)
