#!/usr/bin/env python

import argparse
import os
import re

max_name_len = 60

re_name = re.compile(r'^[a-z][a-z0-9_]*$')
re_group = re.compile(r'//BEGIN')
re_option = re.compile(r'extern (Bounded)?Option<[^>]+>')
re_default = re.compile(r' *// *= *(.*)')
groups = []

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
script = os.path.relpath(__file__, root)


# =============================================================================
class Group(object):
    # -------------------------------------------------------------------------
    def __init__(self, desc):
        self.desc = desc
        self.options = []

    # -------------------------------------------------------------------------
    def append(self, option):
        self.options.append(option)


# =============================================================================
class Option(object):
    # -------------------------------------------------------------------------
    def __init__(self, name, dval, decl, desc):
        if re_name.match(name) is None:
            raise ValueError('{!r} is not a valid option name'.format(name))
        if len(name) > max_name_len:
            raise ValueError(
                '{!r} (length={:d}) exceeds the maximum length {:d}'.format(
                    name, len(name), max_name_len))

        self.desc = '\n'.join(desc)
        self.decl = decl[7:]
        self.name = name
        self.dval = dval

    # -------------------------------------------------------------------------
    def write_declaration(self, out):
        out.write('{} {} = {{\n'.format(self.decl, self.name))
        out.write('  "{}",\n'.format(self.name))
        out.write('  u8R"__(\n{}\n)__"'.format(self.desc))
        if self.dval is not None:
            out.write(',\n  {}'.format(self.dval))
        out.write('\n};\n\n')

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


# -----------------------------------------------------------------------------
def extract_default(decl):
    m = re_default.match(decl)
    if m:
        return m.group(1)
    return None


# -----------------------------------------------------------------------------
def write_banner(out, args):
    out.write(
        '/**\n'
        ' * @file {out_name}\n'
        ' * Declaration and initializers for all options.\n'
        ' * Automatically generated by <code>{script}</code>\n'
        ' * from {in_name}.\n'
        ' */\n'
        '\n'.format(
            in_name=os.path.basename(args.header),
            out_name=os.path.basename(args.output),
            script=script))


# -----------------------------------------------------------------------------
def write_declarations(out, args):
    for group in groups:
        for option in group.options:
            option.write_declaration(out)


# -----------------------------------------------------------------------------
def write_registrations(out, args):
    for group in groups:
        out.write('\n  begin_option_group(u8R"__(\n{}\n)__");\n\n'.format(
            group.desc))

        for option in group.options:
            out.write('  register_option(&options::{});\n'.format(option.name))


# -----------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description='Generate options.cpp')
    parser.add_argument('output', type=str,
                        help='location of options.cpp to write')
    parser.add_argument('header', type=str,
                        help='location of options.h to read')
    parser.add_argument('template', type=str,
                        help='location of options.cpp.in to use as template')
    args = parser.parse_args()

    with open(args.header, 'rt') as f:
        desc = []
        for line in iter(f.readline, b''):
            line = line.strip()

            if re_group.match(line):
                groups.append(Group(line[8:]))

            elif not len(line):
                desc = []

            elif line == '//':
                desc.append('')

            elif line.startswith('// '):
                desc.append(line[3:])

            elif re_option.match(line):
                n, d = f.readline().split(';')
                o = Option(n, extract_default(d.strip()), line, desc)
                groups[-1].append(o)

    replacements = {
        '##BANNER##': write_banner,
        '##DECLARATIONS##': write_declarations,
        '##REGISTRATIONS##': write_registrations,
    }

    with open(args.output, 'wt') as out:
        with open(args.template, 'rt') as t:
            for line in t:
                directive = line.strip()
                if directive in replacements:
                    replacements[directive](out, args)
                else:
                    out.write(line)

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


if __name__ == '__main__':
    main()
