// *INDENT-OFF*

#include "token_enum.h"

//! type that stores two chunks between those no space shall occur
struct no_space_table_t
{
   E_Token first;  //! first  chunk
   E_Token second; //! second chunk
};

/**
 * this table lists out all combos where a space MUST be present
 * E_Token::UNKNOWN is a wildcard.
 *
 * TODO: some of these are no longer needed.
 */
const no_space_table_t add_space_table[] =
{
   { E_Token::ACCESS,                E_Token::TYPE                  },
   { E_Token::ACCESS,                E_Token::WORD                  },
   { E_Token::ALIGN,                 E_Token::PAREN_OPEN            },
   { E_Token::AMP,                   E_Token::WORD                  },
   { E_Token::ANGLE_CLOSE,           E_Token::BRACE_OPEN            },
   { E_Token::ANNOTATION,            E_Token::ANNOTATION            },
   { E_Token::ANNOTATION,            E_Token::TYPE                  },
   { E_Token::ASM_COLON,             E_Token::ASM_COLON             },
   { E_Token::ASM_COLON,             E_Token::STRING                },
   { E_Token::ASM,                   E_Token::FUNC_CALL             },
   { E_Token::ASM,                   E_Token::PAREN_OPEN            },
   { E_Token::ASM,                   E_Token::QUALIFIER             },
   { E_Token::ASSERT,                E_Token::PAREN_OPEN            },
   { E_Token::ASSIGN_FUNC_PROTO,     E_Token::DEFAULT               },
   { E_Token::ASSIGN_FUNC_PROTO,     E_Token::DELETE                },
   { E_Token::ASSIGN_FUNC_PROTO,     E_Token::NUMBER                },
   { E_Token::ATTRIBUTE,             E_Token::ATTRIBUTE             },
   { E_Token::ATTRIBUTE,             E_Token::BRACE_OPEN            },
   { E_Token::ATTRIBUTE,             E_Token::CASE                  },
   { E_Token::ATTRIBUTE,             E_Token::QUALIFIER             },
   { E_Token::ATTRIBUTE,             E_Token::TYPE                  },
   { E_Token::ATTRIBUTE,             E_Token::WORD                  },
   { E_Token::AUTORELEASEPOOL,       E_Token::BRACE_OPEN            },
   { E_Token::BODY,                  E_Token::BRACE_OPEN            },
   { E_Token::BRACE_CLOSE,           E_Token::BRACE_OPEN            },
   { E_Token::BRACE_CLOSE,           E_Token::CLASS                 },
   { E_Token::BRACE_CLOSE,           E_Token::FUNC_CALL             },
   { E_Token::BRACE_CLOSE,           E_Token::GETSET                },
   { E_Token::BRACE_CLOSE,           E_Token::IF                    },
   { E_Token::BRACE_CLOSE,           E_Token::OC_MSG_NAME           },
   { E_Token::BRACE_CLOSE,           E_Token::PAREN_OPEN            },
   { E_Token::BRACE_CLOSE,           E_Token::QUALIFIER             },
   { E_Token::BRACE_CLOSE,           E_Token::RETURN                },
   { E_Token::BRACE_CLOSE,           E_Token::TYPE                  },
   { E_Token::BRACE_CLOSE,           E_Token::WORD                  },
   { E_Token::BREAK,                 E_Token::WORD                  },
   { E_Token::BYREF,                 E_Token::INV                   },
   { E_Token::CASE_COLON,            E_Token::ATTRIBUTE             },
   { E_Token::CASE_COLON,            E_Token::BRACE_OPEN            },
   { E_Token::CASE_COLON,            E_Token::BREAK                 },
   { E_Token::CASE_COLON,            E_Token::RETURN                },
   { E_Token::CASE_COLON,            E_Token::WORD                  },
   { E_Token::CASE,                  E_Token::NEG                   },
   { E_Token::CASE,                  E_Token::PAREN_OPEN            },
   { E_Token::CASE,                  E_Token::STRING                },
   { E_Token::CATCH,                 E_Token::FUNC_CALL             },
   { E_Token::CLASS_COLON,           E_Token::FUNC_CALL             },
   { E_Token::CLASS_COLON,           E_Token::QUALIFIER             },
   { E_Token::CLASS_COLON,           E_Token::TYPE                  },
   { E_Token::CLASS_COLON,           E_Token::WORD                  },
   { E_Token::COLON,                 E_Token::COLON                 },
   { E_Token::COLON,                 E_Token::NUMBER                },
   { E_Token::COLON,                 E_Token::QUALIFIER             },
   { E_Token::COLON,                 E_Token::STRING                },
   { E_Token::COLON,                 E_Token::TYPE                  },
   { E_Token::COLON,                 E_Token::WORD                  },
   { E_Token::COMMENT_EMBED,         E_Token::FUNC_CLASS_PROTO      },
   { E_Token::COMMENT_MULTI,         E_Token::ELSE                  },
   { E_Token::CONCAT,                E_Token::STRING                },
   { E_Token::CONCAT,                E_Token::WORD                  },
   { E_Token::COND_COLON,            E_Token::FUNC_CALL             },
   { E_Token::COND_COLON,            E_Token::STRING                },
   { E_Token::COND_COLON,            E_Token::WORD                  },
   { E_Token::CONSTRUCT,             E_Token::TYPE                  },
   { E_Token::CONTINUE,              E_Token::WORD                  },
   { E_Token::CS_PROPERTY,           E_Token::BRACE_OPEN            },
   { E_Token::DEFAULT,               E_Token::STRING                },
   { E_Token::DEFAULT,               E_Token::WORD                  },
   { E_Token::DELEGATE,              E_Token::BRACE_OPEN            },
   { E_Token::D_MODULE,              E_Token::WORD                  },
   { E_Token::ELLIPSIS,              E_Token::NUMBER                },
   { E_Token::ELSE,                  E_Token::FOR                   },
   { E_Token::ELSE,                  E_Token::IF                    },
   { E_Token::ELSE,                  E_Token::PAREN_OPEN            },
   { E_Token::ELSE,                  E_Token::WORD                  },
   { E_Token::ELSEIF,                E_Token::CONSTEXPR             },
   { E_Token::ENUM_CLASS,            E_Token::ATTRIBUTE             },
   { E_Token::ENUM_CLASS,            E_Token::TYPE                  },
   { E_Token::ENUM,                  E_Token::ATTRIBUTE             },
   { E_Token::ENUM,                  E_Token::BRACE_OPEN            },
   { E_Token::ENUM,                  E_Token::ENUM_CLASS            },
   { E_Token::ENUM,                  E_Token::FPAREN_OPEN           },
   { E_Token::ENUM,                  E_Token::FUNCTION              },
   { E_Token::ENUM,                  E_Token::TYPE                  },
   { E_Token::ENUM,                  E_Token::WORD                  },
   { E_Token::EXECUTION_CONTEXT,     E_Token::EXECUTION_CONTEXT     },
   { E_Token::EXECUTION_CONTEXT,     E_Token::FPAREN_OPEN           },
   { E_Token::EXTERN,                E_Token::STRING                },
   { E_Token::FPAREN_CLOSE,          E_Token::ASSIGN_FUNC_PROTO     },
   { E_Token::FPAREN_CLOSE,          E_Token::ATTRIBUTE             },
   { E_Token::FPAREN_CLOSE,          E_Token::CLASS_COLON           },
   { E_Token::FPAREN_CLOSE,          E_Token::COND_COLON            },
   { E_Token::FPAREN_CLOSE,          E_Token::DEFAULT               },
   { E_Token::FPAREN_CLOSE,          E_Token::FUNC_CALL             },
   { E_Token::FPAREN_CLOSE,          E_Token::NEG                   },
   { E_Token::FPAREN_CLOSE,          E_Token::NOT                   },
   { E_Token::FPAREN_CLOSE,          E_Token::OC_MSG_NAME           },
   { E_Token::FPAREN_CLOSE,          E_Token::QUESTION              },
   { E_Token::FPAREN_CLOSE,          E_Token::STRING                },
   { E_Token::FPAREN_CLOSE,          E_Token::THROW                 },
   { E_Token::FPAREN_CLOSE,          E_Token::TYPE                  },
   { E_Token::FPAREN_CLOSE,          E_Token::WHERE_SPEC            },
   { E_Token::FPAREN_CLOSE,          E_Token::WORD                  },
   { E_Token::FRIEND,                E_Token::CLASS                 },
   { E_Token::FRIEND,                E_Token::STRUCT                },
   { E_Token::FRIEND,                E_Token::TYPE                  },
   { E_Token::FUNCTION,              E_Token::PAREN_OPEN            },
   { E_Token::FUNC_VAR,              E_Token::PPAREN_CLOSE          },
   { E_Token::GOTO,                  E_Token::WORD                  },
   { E_Token::IF,                    E_Token::CONSTEXPR             },
   { E_Token::IGNORED,               E_Token::IGNORED               },
   { E_Token::IMPORT,                E_Token::WORD                  },
   { E_Token::INCDEC_AFTER,          E_Token::DEREF                 },
   { E_Token::IN,                    E_Token::TYPE                  },
   { E_Token::IN,                    E_Token::WORD                  },
   { E_Token::LABEL_COLON,           E_Token::CS_PROPERTY           },
   { E_Token::LABEL_COLON,           E_Token::FUNC_CALL             },
   { E_Token::LABEL_COLON,           E_Token::NEW                   },
   { E_Token::LABEL_COLON,           E_Token::PAREN_OPEN            },
   { E_Token::LABEL_COLON,           E_Token::RETURN                },
   { E_Token::LABEL_COLON,           E_Token::STRING                },
   { E_Token::LABEL_COLON,           E_Token::TYPE                  },
   { E_Token::LABEL_COLON,           E_Token::WORD                  },
   { E_Token::LOCK,                  E_Token::PAREN_OPEN            },
   { E_Token::NAMESPACE,             E_Token::BRACE_OPEN            },
   { E_Token::NAMESPACE,             E_Token::TYPE                  },
   { E_Token::NAMESPACE,             E_Token::WORD                  },
   { E_Token::NATIVE,                E_Token::TAG                   },
   { E_Token::NUMBER,                E_Token::CHAR                  },
   { E_Token::NUMBER,                E_Token::COLON                 },
   { E_Token::NUMBER,                E_Token::ELLIPSIS              },
   { E_Token::NUMBER,                E_Token::OC_MSG_NAME           },
   { E_Token::NUMBER,                E_Token::PAREN_OPEN            },
   { E_Token::NUMBER,                E_Token::WORD                  },
   { E_Token::NUMBER_FP,             E_Token::NUMBER                },
   { E_Token::NUMBER_FP,             E_Token::OC_MSG_NAME           },
   { E_Token::NUMBER_FP,             E_Token::WORD                  },
   { E_Token::OC_CLASS,              E_Token::CLASS_COLON           },
   { E_Token::OC_CLASS,              E_Token::PAREN_OPEN            },
   { E_Token::OC_DYNAMIC,            E_Token::WORD                  },
   { E_Token::OC_IMPL,               E_Token::OC_CLASS              },
   { E_Token::OC_INTF,               E_Token::OC_CLASS              },
   { E_Token::OC_MSG_DECL,           E_Token::BRACE_OPEN            },
   { E_Token::OC_PROTOCOL,           E_Token::OC_CLASS              },
   { E_Token::PACKAGE,               E_Token::WORD                  },
   { E_Token::PAREN_CLOSE,           E_Token::ASM_COLON             },
   { E_Token::PAREN_CLOSE,           E_Token::COLON                 },
   { E_Token::PAREN_CLOSE,           E_Token::COND_COLON            },
   { E_Token::PAREN_CLOSE,           E_Token::CS_PROPERTY           },
   { E_Token::PAREN_CLOSE,           E_Token::DEREF                 },
   { E_Token::PAREN_CLOSE,           E_Token::NOT                   },
   { E_Token::PAREN_CLOSE,           E_Token::NUMBER                },
   { E_Token::PAREN_CLOSE,           E_Token::OC_MSG_NAME           },
   { E_Token::PAREN_CLOSE,           E_Token::POS                   },
   { E_Token::PAREN_CLOSE,           E_Token::QUALIFIER             },
   { E_Token::PAREN_CLOSE,           E_Token::TYPE                  },
   { E_Token::PP_DEFINE,             E_Token::MACRO                 },
   { E_Token::PP_DEFINE,             E_Token::MACRO_FUNC            },
   { E_Token::PP_DEFINE,             E_Token::NUMBER                },
   { E_Token::PP_DEFINE,             E_Token::PP_IGNORE             },
   { E_Token::PP_DEFINED,            E_Token::TYPE                  },
   { E_Token::PP_DEFINED,            E_Token::WORD                  },
   { E_Token::PP_ELSE,               E_Token::FUNC_CALL             },
   { E_Token::PP_ELSE,               E_Token::NOT                   },
   { E_Token::PP_ELSE,               E_Token::NUMBER                },
   { E_Token::PP_ELSE,               E_Token::PAREN_OPEN            },
   { E_Token::PP_ELSE,               E_Token::PP_DEFINED            },
   { E_Token::PP_ELSE,               E_Token::WORD                  },
   { E_Token::PP_EMIT,               E_Token::MACRO                 },
   { E_Token::PP_ENDIF,              E_Token::WORD                  },
   { E_Token::PP_ENDREGION,          E_Token::PREPROC_BODY          },
   { E_Token::PP_IF,                 E_Token::CNG_HASINC            },
   { E_Token::PP_IF,                 E_Token::FUNC_CALL             },
   { E_Token::PP_IF,                 E_Token::NOT                   },
   { E_Token::PP_IF,                 E_Token::NUMBER                },
   { E_Token::PP_IF,                 E_Token::PAREN_OPEN            },
   { E_Token::PP_IF,                 E_Token::PP_ASM                },
   { E_Token::PP_IF,                 E_Token::PP_DEFINE             },
   { E_Token::PP_IF,                 E_Token::PP_DEFINED            },
   { E_Token::PP_IF,                 E_Token::TYPE                  },
   { E_Token::PP_IF,                 E_Token::WORD                  },
   { E_Token::PP_INCLUDE,            E_Token::STRING                },
   { E_Token::PP_INCLUDE,            E_Token::WORD                  },
   { E_Token::PP_OTHER,              E_Token::PREPROC_BODY          },
   { E_Token::PP_PRAGMA,             E_Token::PP_ENDASM             },
   { E_Token::PP_PRAGMA,             E_Token::PP_ENDREGION          },
   { E_Token::PP_PRAGMA,             E_Token::PP_REGION             },
   { E_Token::PP_PROPERTY,           E_Token::WORD                  },
   { E_Token::PP_REGION,             E_Token::IGNORED               },
   { E_Token::PP_REGION,             E_Token::PREPROC_BODY          },
   { E_Token::PP_UNDEF,              E_Token::TYPE                  },
   { E_Token::PP_UNDEF,              E_Token::WORD                  },
   { E_Token::Q_EMIT,                E_Token::FUNC_CALL             },
   { E_Token::Q_FOREVER,             E_Token::BRACE_OPEN            },
   { E_Token::QUESTION,              E_Token::FUNC_CALL             },
   { E_Token::QUESTION,              E_Token::PAREN_OPEN            },
   { E_Token::QUESTION,              E_Token::STRING                },
   { E_Token::QUESTION,              E_Token::WORD                  },
   { E_Token::SBOOL,                 E_Token::TYPE                  },
   { E_Token::SCOMPARE,              E_Token::WORD                  },
   { E_Token::SPAREN_CLOSE,          E_Token::ATTRIBUTE             },
   { E_Token::SPAREN_CLOSE,          E_Token::AUTORELEASEPOOL       },
   { E_Token::SPAREN_CLOSE,          E_Token::BRACE_OPEN            },
   { E_Token::SPAREN_CLOSE,          E_Token::FUNC_CALL             },
   { E_Token::SPAREN_CLOSE,          E_Token::WORD                  },
   { E_Token::SQL_ASSIGN,            E_Token::FUNC_CALL             },
   { E_Token::SQL_ASSIGN,            E_Token::WORD                  },
   { E_Token::SQL_BEGIN,             E_Token::SQL_WORD              },
   { E_Token::SQL_END,               E_Token::SQL_WORD              },
   { E_Token::SQL_EXEC,              E_Token::SQL_WORD              },
   { E_Token::SQL_WORD,              E_Token::COLON                 },
   { E_Token::SQL_WORD,              E_Token::PAREN_OPEN            },
   { E_Token::SQL_WORD,              E_Token::SQL_WORD              },
   { E_Token::SQUARE_CLOSE,          E_Token::ATTRIBUTE             },
   { E_Token::SQUARE_CLOSE,          E_Token::BRACE_OPEN            },
   { E_Token::SQUARE_CLOSE,          E_Token::COLON                 },
   { E_Token::SQUARE_CLOSE,          E_Token::EXECUTION_CONTEXT     },
   { E_Token::SQUARE_CLOSE,          E_Token::OC_MSG_NAME           },
   { E_Token::SQUARE_CLOSE,          E_Token::STRING                },
   { E_Token::SQUARE_CLOSE,          E_Token::WORD                  },
   { E_Token::STATE,                 E_Token::TYPE                  },
   { E_Token::STOCK,                 E_Token::QUALIFIER             },
   { E_Token::STOCK,                 E_Token::TAG                   },
   { E_Token::STRING,                E_Token::ATTRIBUTE             },
   { E_Token::STRING,                E_Token::BRACE_OPEN            },
   { E_Token::STRING,                E_Token::COLON                 },
   { E_Token::STRING,                E_Token::CONCAT                },
   { E_Token::STRING,                E_Token::OC_MSG_NAME           },
   { E_Token::STRING,                E_Token::PAREN_OPEN            },
   { E_Token::STRING,                E_Token::STRUCT                },
   { E_Token::STRING,                E_Token::TYPE                  },
   { E_Token::STRING,                E_Token::WORD                  },
   { E_Token::STRUCT,                E_Token::BRACE_OPEN            },
   { E_Token::STRUCT,                E_Token::CLASS_COLON           },
   { E_Token::STRUCT,                E_Token::MACRO_FUNC_CALL       },
   { E_Token::STRUCT,                E_Token::WORD                  },
   { E_Token::TEMPLATE,              E_Token::CLASS                 },
   { E_Token::TEMPLATE,              E_Token::TYPE                  },
   { E_Token::THIS,                  E_Token::OC_MSG_NAME           },
   { E_Token::THIS,                  E_Token::TYPE                  },
   { E_Token::TSQUARE,               E_Token::BRACE_OPEN            },
   { E_Token::TSQUARE,               E_Token::PAREN_OPEN            },
   { E_Token::TSQUARE,               E_Token::WORD                  },
   { E_Token::TYPEDEF,               E_Token::ENUM                  },
   { E_Token::TYPEDEF,               E_Token::FUNC_TYPE             },
   { E_Token::TYPEDEF,               E_Token::PAREN_OPEN            },
   { E_Token::TYPEDEF,               E_Token::QUALIFIER             },
   { E_Token::TYPEDEF,               E_Token::STRUCT                },
   { E_Token::TYPEDEF,               E_Token::TYPE                  },
   { E_Token::TYPEDEF,               E_Token::TYPENAME              },
   { E_Token::TYPEDEF,               E_Token::UNION                 },
   { E_Token::TYPENAME,              E_Token::ELLIPSIS              },
   { E_Token::TYPENAME,              E_Token::WORD                  },
   { E_Token::UNION,                 E_Token::BRACE_OPEN            },
   { E_Token::UNION,                 E_Token::TYPE                  },
   { E_Token::UNION,                 E_Token::WORD                  },
   { E_Token::USING,                 E_Token::NAMESPACE             },
   { E_Token::USING,                 E_Token::TYPE                  },
   { E_Token::USING,                 E_Token::WORD                  },
   { E_Token::USING_STMT,            E_Token::PAREN_OPEN            },
   { E_Token::VOLATILE,              E_Token::BRACE_OPEN            },
   { E_Token::WHERE_COLON,           E_Token::CS_PROPERTY           },
   { E_Token::WHERE_COLON,           E_Token::NEW                   },
   { E_Token::WHERE_COLON,           E_Token::TYPE                  },
   { E_Token::WHERE_COLON,           E_Token::WORD                  },
   { E_Token::WHERE_SPEC,            E_Token::WORD                  },
   { E_Token::WORD,                  E_Token::ATTRIBUTE             },
   { E_Token::WORD,                  E_Token::BRACE_OPEN            },
   { E_Token::WORD,                  E_Token::CLASS_COLON           },
   { E_Token::WORD,                  E_Token::COLON                 },
   { E_Token::WORD,                  E_Token::COMMENT_CPP           },
   { E_Token::WORD,                  E_Token::CONCAT                },
   { E_Token::WORD,                  E_Token::ELLIPSIS              },
   { E_Token::WORD,                  E_Token::IN                    },
   { E_Token::WORD,                  E_Token::NEW                   },
   { E_Token::WORD,                  E_Token::NOT                   },
   { E_Token::WORD,                  E_Token::NUMBER                },
   { E_Token::WORD,                  E_Token::NUMBER_FP             },
   { E_Token::WORD,                  E_Token::OPERATOR              },
   { E_Token::WORD,                  E_Token::QUALIFIER             },
   { E_Token::WORD,                  E_Token::QUESTION              },
   { E_Token::WORD,                  E_Token::SCOMPARE              },
   { E_Token::WORD,                  E_Token::SQL_ASSIGN            },
   { E_Token::WORD,                  E_Token::STRING                },
   { E_Token::WORD,                  E_Token::STRUCT                },
   { E_Token::WORD,                  E_Token::TYPE                  },
   { E_Token::WORD,                  E_Token::TYPE_CAST             },
   { E_Token::WORD,                  E_Token::TYPEDEF               },
   { E_Token::WORD,                  E_Token::WHERE_COLON           },
   { E_Token::WORD,                  E_Token::WHERE_SPEC            },
   { E_Token::WORD,                  E_Token::WORD                  },
};

/**
 * this table lists out all combos where a space should NOT be present
 * E_Token::UNKNOWN is a wildcard.
 *
 * TODO: some of these are no longer needed.
 */
const no_space_table_t no_space_table[] =
{
   { E_Token::OC_AT,          E_Token::UNKNOWN      },
   { E_Token::INCDEC_BEFORE,  E_Token::WORD         },
   { E_Token::UNKNOWN,        E_Token::INCDEC_AFTER },
   { E_Token::UNKNOWN,        E_Token::LABEL_COLON  },
   { E_Token::UNKNOWN,        E_Token::ACCESS_COLON },
   { E_Token::UNKNOWN,        E_Token::SEMICOLON    },
   { E_Token::UNKNOWN,        E_Token::D_TEMPLATE   },
   { E_Token::D_TEMPLATE,     E_Token::UNKNOWN      },
   { E_Token::MACRO_FUNC,     E_Token::FPAREN_OPEN  },
   { E_Token::PAREN_OPEN,     E_Token::UNKNOWN      },
   { E_Token::UNKNOWN,        E_Token::PAREN_CLOSE  },
   { E_Token::FPAREN_OPEN,    E_Token::UNKNOWN      },
   { E_Token::UNKNOWN,        E_Token::SPAREN_CLOSE },
   { E_Token::SPAREN_OPEN,    E_Token::UNKNOWN      },
   { E_Token::UNKNOWN,        E_Token::FPAREN_CLOSE },
   { E_Token::UNKNOWN,        E_Token::COMMA        },
   { E_Token::POS,            E_Token::UNKNOWN      },
   { E_Token::STAR,           E_Token::UNKNOWN      },
   { E_Token::VBRACE_CLOSE,   E_Token::UNKNOWN      },
   { E_Token::VBRACE_OPEN,    E_Token::UNKNOWN      },
   { E_Token::UNKNOWN,        E_Token::VBRACE_CLOSE },
   { E_Token::UNKNOWN,        E_Token::VBRACE_OPEN  },
   { E_Token::PREPROC,        E_Token::UNKNOWN      },
   { E_Token::PREPROC_INDENT, E_Token::UNKNOWN      },
   { E_Token::NEG,            E_Token::UNKNOWN      },
   { E_Token::UNKNOWN,        E_Token::SQUARE_OPEN  },
   { E_Token::UNKNOWN,        E_Token::SQUARE_CLOSE },
   { E_Token::SQUARE_OPEN,    E_Token::UNKNOWN      },
   { E_Token::PAREN_CLOSE,    E_Token::WORD         },
   { E_Token::PAREN_CLOSE,    E_Token::FUNC_DEF     },
   { E_Token::PAREN_CLOSE,    E_Token::FUNC_CALL    },
   { E_Token::PAREN_CLOSE,    E_Token::ADDR         },
   { E_Token::PAREN_CLOSE,    E_Token::FPAREN_OPEN  },
   { E_Token::OC_SEL_NAME,    E_Token::OC_SEL_NAME  },
   { E_Token::TYPENAME,       E_Token::TYPE         },
};

/**
 * this table lists out all combos where nothing is to do
 * E_Token::UNKNOWN is a wildcard.
 *
 * TODO: some of these are no longer needed.
 */
const no_space_table_t IGNORE_space_table[] =
{
   { E_Token::NUMBER_FP,    E_Token::PAREN_OPEN},
   { E_Token::PAREN_CLOSE,    E_Token::SIZEOF},
   { E_Token::SQUARE_CLOSE,   E_Token::INCDEC_BEFORE},
};


// *INDENT-ON*
