#ifndef CHUNK_TAG_T_H_INCLUDED
#define CHUNK_TAG_T_H_INCLUDED
static chunk_tag_t keywords[] =
{
   // TODO: it might be useful if users could add their custom keywords to this list
   { "@autoreleasepool",                E_Token::AUTORELEASEPOOL,  e_LANG_OC                                                                                 },
   { "@available",                      E_Token::OC_AVAILABLE,     e_LANG_OC                                                                                 },
   { "@catch",                          E_Token::CATCH,            e_LANG_OC                                                                                 },
   { "@dynamic",                        E_Token::OC_DYNAMIC,       e_LANG_OC                                                                                 },
   { "@end",                            E_Token::OC_END,           e_LANG_OC                                                                                 },
   { "@finally",                        E_Token::FINALLY,          e_LANG_OC                                                                                 },
   { "@implementation",                 E_Token::OC_IMPL,          e_LANG_OC                                                                                 },
   { "@interface",                      E_Token::OC_INTF,          e_LANG_OC                                                                                 },
   { "@interface",                      E_Token::CLASS,            e_LANG_JAVA                                                                               },
   { "@private",                        E_Token::ACCESS,           e_LANG_OC                                                                                 },
   { "@property",                       E_Token::OC_PROPERTY,      e_LANG_OC                                                                                 },
   { "@protected",                      E_Token::ACCESS,           e_LANG_OC                                                                                 },
   { "@protocol",                       E_Token::OC_PROTOCOL,      e_LANG_OC                                                                                 },
   { "@public",                         E_Token::ACCESS,           e_LANG_OC                                                                                 },
   { "@selector",                       E_Token::OC_SEL,           e_LANG_OC                                                                                 },
   { "@synchronized",                   E_Token::SYNCHRONIZED,     e_LANG_OC                                                                                 },
   { "@synthesize",                     E_Token::OC_DYNAMIC,       e_LANG_OC                                                                                 },
   { "@throw",                          E_Token::THROW,            e_LANG_OC                                                                                 },
   { "@try",                            E_Token::TRY,              e_LANG_OC                                                                                 },
   { "API_AVAILABLE",                   E_Token::ATTRIBUTE,        e_LANG_OC                                                                                 },
   { "API_DEPRECATED",                  E_Token::ATTRIBUTE,        e_LANG_OC                                                                                 },
   { "API_DEPRECATED_WITH_REPLACEMENT", E_Token::ATTRIBUTE,        e_LANG_OC                                                                                 },
   { "API_UNAVAILABLE",                 E_Token::ATTRIBUTE,        e_LANG_OC                                                                                 },
   { "BOOL",                            E_Token::TYPE,             e_LANG_OC                                                                                 },
   { "INT16_C",                         E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "INT32_C",                         E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "INT64_C",                         E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "INT8_C",                          E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "INTMAX_C",                        E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "NS_CLOSED_ENUM",                  E_Token::ENUM,             e_LANG_C | e_LANG_OC                                                                      },
   { "NS_ENUM",                         E_Token::ENUM,             e_LANG_C | e_LANG_OC                                                                      },
   { "NS_ERROR_ENUM",                   E_Token::ENUM,             e_LANG_C | e_LANG_OC                                                                      },
   { "NS_OPTIONS",                      E_Token::ENUM,             e_LANG_C | e_LANG_OC                                                                      },
   { "Q_EMIT",                          E_Token::Q_EMIT,           e_LANG_CPP                                                                                },
   { "Q_FOREACH",                       E_Token::Q_FOREACH,        e_LANG_CPP                                                                                },
   { "Q_FOREVER",                       E_Token::Q_FOREVER,        e_LANG_CPP                                                                                },
   { "Q_GADGET",                        E_Token::Q_GADGET,         e_LANG_CPP                                                                                },
   { "Q_OBJECT",                        E_Token::COMMENT_EMBED,    e_LANG_CPP                                                                                },
   { "Q_SIGNALS",                       E_Token::ACCESS,           e_LANG_CPP                                                                                },
   { "UINT16_C",                        E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "UINT32_C",                        E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "UINT64_C",                        E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "UINT8_C",                         E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "UINTMAX_C",                       E_Token::TYPE,             e_LANG_CPP                                                                                },
   { "_Bool",                           E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "_Complex",                        E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "_Imaginary",                      E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "_Nonnull",                        E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "_Null_unspecified",               E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "_Nullable",                       E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "_Pragma",                         E_Token::PP_PRAGMA,        e_LANG_ALL | e_FLAG_PP                                                                    },
   { "__DI__",                          E_Token::DI,               e_LANG_C | e_LANG_CPP                                                                     },
   { "__HI__",                          E_Token::HI,               e_LANG_C | e_LANG_CPP                                                                     },
   { "__QI__",                          E_Token::QI,               e_LANG_C | e_LANG_CPP                                                                     },
   { "__SI__",                          E_Token::SI,               e_LANG_C | e_LANG_CPP                                                                     },
   { "__asm__",                         E_Token::ASM,              e_LANG_C | e_LANG_CPP                                                                     },
   { "__attribute__",                   E_Token::ATTRIBUTE,        e_LANG_C | e_LANG_CPP | e_LANG_OC                                                         },
   { "__autoreleasing",                 E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__block",                         E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP | e_LANG_OC                                                         },
   { "__bridge",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__bridge_retained",               E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__bridge_transfer",               E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__const__",                       E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__declspec",                      E_Token::DECLSPEC,         e_LANG_C | e_LANG_CPP                                                                     },
   { "__except",                        E_Token::CATCH,            e_LANG_C | e_LANG_CPP                                                                     },
   { "__finally",                       E_Token::FINALLY,          e_LANG_C | e_LANG_CPP                                                                     },
   { "__has_include",                   E_Token::CNG_HASINC,       e_LANG_C | e_LANG_CPP | e_LANG_OC | e_FLAG_PP                                             },
   { "__has_include_next",              E_Token::CNG_HASINCN,      e_LANG_C | e_LANG_CPP | e_FLAG_PP                                                         },
   { "__inline__",                      E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__nonnull",                       E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "__nothrow__",                     E_Token::NOTHROW,          e_LANG_C | e_LANG_CPP                                                                     },
   { "__null_unspecified",              E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "__nullable",                      E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "__pragma",                        E_Token::PP_PRAGMA,        e_LANG_ALL | e_FLAG_PP                                                                    },
   { "__restrict",                      E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__signed__",                      E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "__strong",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__thread",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__traits",                        E_Token::QUALIFIER,        e_LANG_D                                                                                  },
   { "__try",                           E_Token::TRY,              e_LANG_C | e_LANG_CPP                                                                     },
   { "__typeof",                        E_Token::DECLTYPE,         e_LANG_C | e_LANG_CPP | e_LANG_OC                                                         },
   { "__typeof__",                      E_Token::DECLTYPE,         e_LANG_C | e_LANG_CPP                                                                     },
   { "__unsafe_unretained",             E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "__unused",                        E_Token::ATTRIBUTE,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__volatile__",                    E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__weak",                          E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "__word__",                        E_Token::WORD_,            e_LANG_C | e_LANG_CPP                                                                     },
   { "abstract",                        E_Token::QUALIFIER,        e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_VALA | e_LANG_ECMA                            },
   { "add",                             E_Token::GETSET,           e_LANG_CS                                                                                 },
   { "alias",                           E_Token::USING,            e_LANG_D                                                                                  },
   { "align",                           E_Token::ALIGN,            e_LANG_D                                                                                  },
   { "alignof",                         E_Token::SIZEOF,           e_LANG_CPP                                                                                },
   { "and",                             E_Token::SBOOL,            e_LANG_CPP                                                                                },
   { "and_eq",                          E_Token::SASSIGN,          e_LANG_CPP                                                                                },
   { "as",                              E_Token::AS,               e_LANG_CS | e_LANG_VALA                                                                   },
   { "asm",                             E_Token::ASM,              e_LANG_C | e_LANG_CPP | e_LANG_D                                                          },
   { "asm",                             E_Token::PP_ASM,           e_LANG_ALL | e_FLAG_PP                                                                    },
   { "assert",                          E_Token::ASSERT,           e_LANG_JAVA                                                                               },
   { "assert",                          E_Token::FUNCTION,         e_LANG_D | e_LANG_PAWN                                                                    },
   { "assert",                          E_Token::PP_ASSERT,        e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "async",                           E_Token::QUALIFIER,        e_LANG_VALA                                                                               },
   { "auto",                            E_Token::TYPE,             e_LANG_C | e_LANG_CPP | e_LANG_D                                                          },
   { "base",                            E_Token::BASE,             e_LANG_CS | e_LANG_VALA                                                                   },
   { "bit",                             E_Token::TYPE,             e_LANG_D                                                                                  },
   { "bitand",                          E_Token::ARITH,            e_LANG_C | e_LANG_CPP                                                                     },
   { "bitor",                           E_Token::ARITH,            e_LANG_C | e_LANG_CPP                                                                     },
   { "body",                            E_Token::BODY,             e_LANG_D                                                                                  },
   { "bool",                            E_Token::TYPE,             e_LANG_C | e_LANG_CPP | e_LANG_CS | e_LANG_VALA                                           },
   { "boolean",                         E_Token::TYPE,             e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "break",                           E_Token::BREAK,            e_LANG_ALL                                                                                },
   { "byte",                            E_Token::TYPE,             e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_ECMA                                          },
   { "case",                            E_Token::CASE,             e_LANG_ALL                                                                                },
   { "cast",                            E_Token::D_CAST,           e_LANG_D                                                                                  },
   { "catch",                           E_Token::CATCH,            e_LANG_CPP | e_LANG_CS | e_LANG_VALA | e_LANG_D | e_LANG_JAVA | e_LANG_ECMA               },
   { "cdouble",                         E_Token::TYPE,             e_LANG_D                                                                                  },
   { "cent",                            E_Token::TYPE,             e_LANG_D                                                                                  },
   { "cfloat",                          E_Token::TYPE,             e_LANG_D                                                                                  },
   { "char",                            E_Token::CHAR,             e_LANG_PAWN                                                                               },
   { "char",                            E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "checked",                         E_Token::QUALIFIER,        e_LANG_CS                                                                                 },
   { "class",                           E_Token::CLASS,            e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_VALA | e_LANG_ECMA               },
   { "compl",                           E_Token::ARITH,            e_LANG_CPP                                                                                },
   { "const",                           E_Token::QUALIFIER,        e_LANG_ALL                                                                                },
   { "const_cast",                      E_Token::TYPE_CAST,        e_LANG_CPP                                                                                },
   { "constexpr",                       E_Token::QUALIFIER,        e_LANG_CPP                                                                                },
   { "construct",                       E_Token::CONSTRUCT,        e_LANG_VALA                                                                               },
   { "continue",                        E_Token::CONTINUE,         e_LANG_ALL                                                                                },
   { "creal",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "dchar",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "debug",                           E_Token::DEBUG,            e_LANG_D                                                                                  },
   { "debugger",                        E_Token::DEBUGGER,         e_LANG_ECMA                                                                               },
   { "decltype",                        E_Token::DECLTYPE,         e_LANG_CPP                                                                                },
   { "default",                         E_Token::DEFAULT,          e_LANG_ALL                                                                                },
   { "define",                          E_Token::PP_DEFINE,        e_LANG_ALL | e_FLAG_PP                                                                    },
   { "defined",                         E_Token::DEFINED,          e_LANG_PAWN                                                                               },
   { "defined",                         E_Token::PP_DEFINED,       e_LANG_ALLC | e_FLAG_PP                                                                   },
   { "delegate",                        E_Token::DELEGATE,         e_LANG_CS | e_LANG_VALA | e_LANG_D                                                        },
   { "delete",                          E_Token::DELETE,           e_LANG_CPP | e_LANG_D | e_LANG_ECMA | e_LANG_VALA                                         },
   { "deprecated",                      E_Token::QUALIFIER,        e_LANG_D                                                                                  },
   { "do",                              E_Token::DO,               e_LANG_ALL                                                                                },
   { "double",                          E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "dynamic",                         E_Token::QUALIFIER,        e_LANG_VALA                                                                               },
   { "dynamic_cast",                    E_Token::TYPE_CAST,        e_LANG_CPP                                                                                },
   { "elif",                            E_Token::PP_ELSE,          e_LANG_ALLC | e_FLAG_PP                                                                   },
   { "else",                            E_Token::ELSE,             e_LANG_ALL                                                                                },
   { "else",                            E_Token::PP_ELSE,          e_LANG_ALL | e_FLAG_PP                                                                    },
   { "elseif",                          E_Token::PP_ELSE,          e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "emit",                            E_Token::PP_EMIT,          e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "endif",                           E_Token::PP_ENDIF,         e_LANG_ALL | e_FLAG_PP                                                                    },
   { "endinput",                        E_Token::PP_ENDINPUT,      e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "endregion",                       E_Token::PP_ENDREGION,     e_LANG_ALL | e_FLAG_PP                                                                    },
   { "endscript",                       E_Token::PP_ENDINPUT,      e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "enum",                            E_Token::ENUM,             e_LANG_ALL                                                                                },
   { "error",                           E_Token::PP_ERROR,         e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "errordomain",                     E_Token::ENUM,             e_LANG_VALA                                                                               },
   { "event",                           E_Token::TYPE,             e_LANG_CS                                                                                 },
   { "exit",                            E_Token::FUNCTION,         e_LANG_PAWN                                                                               },
   { "explicit",                        E_Token::QUALIFIER,        e_LANG_CPP | e_LANG_CS                                                                    },
   { "export",                          E_Token::EXPORT,           e_LANG_CPP | e_LANG_D | e_LANG_ECMA                                                       },
   { "extends",                         E_Token::QUALIFIER,        e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "extern",                          E_Token::EXTERN,           e_LANG_C | e_LANG_CPP | e_LANG_OC | e_LANG_CS | e_LANG_D | e_LANG_VALA                    },
   { "false",                           E_Token::WORD,             e_LANG_ALL                                                                                },
   { "file",                            E_Token::PP_FILE,          e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "final",                           E_Token::QUALIFIER,        e_LANG_CPP | e_LANG_D | e_LANG_ECMA                                                       },
   { "finally",                         E_Token::FINALLY,          e_LANG_D | e_LANG_CS | e_LANG_VALA | e_LANG_ECMA | e_LANG_JAVA                            },
   { "fixed",                           E_Token::FIXED,            e_LANG_CS                                                                                 },
   { "flags",                           E_Token::TYPE,             e_LANG_VALA                                                                               },
   { "float",                           E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "for",                             E_Token::FOR,              e_LANG_ALL                                                                                },
   { "foreach",                         E_Token::FOR,              e_LANG_CS | e_LANG_D | e_LANG_VALA                                                        },
   { "foreach_reverse",                 E_Token::FOR,              e_LANG_D                                                                                  },
   { "forward",                         E_Token::FORWARD,          e_LANG_PAWN                                                                               },
   { "friend",                          E_Token::FRIEND,           e_LANG_CPP                                                                                },
   { "function",                        E_Token::FUNCTION,         e_LANG_D | e_LANG_ECMA                                                                    },
   { "get",                             E_Token::GETSET,           e_LANG_CS | e_LANG_VALA                                                                   },
   { "goto",                            E_Token::GOTO,             e_LANG_ALL                                                                                },
   { "idouble",                         E_Token::TYPE,             e_LANG_D                                                                                  },
   { "if",                              E_Token::IF,               e_LANG_ALL                                                                                },
   { "if",                              E_Token::PP_IF,            e_LANG_ALL | e_FLAG_PP                                                                    },
   { "ifdef",                           E_Token::PP_IF,            e_LANG_ALLC | e_FLAG_PP                                                                   },
   { "ifloat",                          E_Token::TYPE,             e_LANG_D                                                                                  },
   { "ifndef",                          E_Token::PP_IF,            e_LANG_ALLC | e_FLAG_PP                                                                   },
   { "implements",                      E_Token::QUALIFIER,        e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "implicit",                        E_Token::QUALIFIER,        e_LANG_CS                                                                                 },
   { "import",                          E_Token::IMPORT,           e_LANG_D | e_LANG_JAVA | e_LANG_ECMA                                                      },
   { "import",                          E_Token::PP_INCLUDE,       e_LANG_OC | e_FLAG_PP                                                                     },
   { "in",                              E_Token::IN,               e_LANG_D | e_LANG_CS | e_LANG_VALA | e_LANG_ECMA | e_LANG_OC                              },
   { "include",                         E_Token::PP_INCLUDE,       e_LANG_C | e_LANG_CPP | e_LANG_OC | e_LANG_PAWN | e_FLAG_PP                               },
   { "inline",                          E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "inout",                           E_Token::QUALIFIER,        e_LANG_D                                                                                  },
   { "instanceof",                      E_Token::SIZEOF,           e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "int",                             E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "interface",                       E_Token::CLASS,            e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_VALA | e_LANG_ECMA               },
   { "internal",                        E_Token::QUALIFIER,        e_LANG_CS | e_LANG_VALA                                                                   },
   { "invariant",                       E_Token::INVARIANT,        e_LANG_D                                                                                  },
   { "ireal",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "is",                              E_Token::SCOMPARE,         e_LANG_D | e_LANG_CS | e_LANG_VALA                                                        },
   { "lazy",                            E_Token::LAZY,             e_LANG_D                                                                                  },
   { "line",                            E_Token::PP_LINE,          e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "lock",                            E_Token::LOCK,             e_LANG_CS | e_LANG_VALA                                                                   },
   { "long",                            E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "macro",                           E_Token::D_MACRO,          e_LANG_D                                                                                  },
   { "mixin",                           E_Token::CLASS,            e_LANG_D                                                                                  }, // may need special handling
   { "module",                          E_Token::D_MODULE,         e_LANG_D                                                                                  },
   { "mutable",                         E_Token::QUALIFIER,        e_LANG_CPP                                                                                },
   { "namespace",                       E_Token::NAMESPACE,        e_LANG_CPP | e_LANG_CS | e_LANG_VALA                                                      },
   { "native",                          E_Token::NATIVE,           e_LANG_PAWN                                                                               },
   { "native",                          E_Token::QUALIFIER,        e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "new",                             E_Token::NEW,              e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_PAWN | e_LANG_VALA | e_LANG_ECMA },
   { "noexcept",                        E_Token::NOEXCEPT,         e_LANG_CPP                                                                                },
   { "nonnull",                         E_Token::TYPE,             e_LANG_OC                                                                                 },
   { "not",                             E_Token::SARITH,           e_LANG_CPP                                                                                },
   { "not_eq",                          E_Token::SCOMPARE,         e_LANG_CPP                                                                                },
   { "null_resettable",                 E_Token::OC_PROPERTY_ATTR, e_LANG_OC                                                                                 },
   { "null_unspecified",                E_Token::TYPE,             e_LANG_OC                                                                                 },
   { "nullable",                        E_Token::TYPE,             e_LANG_OC                                                                                 },
   { "object",                          E_Token::TYPE,             e_LANG_CS                                                                                 },
   { "operator",                        E_Token::OPERATOR,         e_LANG_CPP | e_LANG_CS | e_LANG_PAWN                                                      },
   { "or",                              E_Token::SBOOL,            e_LANG_CPP                                                                                },
   { "or_eq",                           E_Token::SASSIGN,          e_LANG_CPP                                                                                },
   { "out",                             E_Token::QUALIFIER,        e_LANG_CS | e_LANG_D | e_LANG_VALA                                                        },
   { "override",                        E_Token::QUALIFIER,        e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_VALA                                           },
   { "owned",                           E_Token::QUALIFIER,        e_LANG_VALA                                                                               },
   { "package",                         E_Token::ACCESS,           e_LANG_D                                                                                  },
   { "package",                         E_Token::PACKAGE,          e_LANG_ECMA | e_LANG_JAVA                                                                 },
   { "params",                          E_Token::TYPE,             e_LANG_CS | e_LANG_VALA                                                                   },
   { "pragma",                          E_Token::PP_PRAGMA,        e_LANG_ALL | e_FLAG_PP                                                                    },
   { "private",                         E_Token::ACCESS,           e_LANG_ALLC_NOT_C                                                                         }, // Issue # 4044
   { "property",                        E_Token::PP_PROPERTY,      e_LANG_CS | e_FLAG_PP                                                                     },
   { "protected",                       E_Token::ACCESS,           e_LANG_ALLC_NOT_C                                                                         }, // Issue # 4044
   { "public",                          E_Token::ACCESS,           e_LANG_ALLC_NOT_C                                                                         }, // Issue # 4044
   { "readonly",                        E_Token::QUALIFIER,        e_LANG_CS                                                                                 },
   { "real",                            E_Token::TYPE,             e_LANG_D                                                                                  },
   { "ref",                             E_Token::QUALIFIER,        e_LANG_CS | e_LANG_VALA                                                                   },
   { "region",                          E_Token::PP_REGION,        e_LANG_ALL | e_FLAG_PP                                                                    },
   { "register",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "reinterpret_cast",                E_Token::TYPE_CAST,        e_LANG_CPP                                                                                },
   { "remove",                          E_Token::GETSET,           e_LANG_CS                                                                                 },
   { "restrict",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP                                                                     },
   { "return",                          E_Token::RETURN,           e_LANG_ALL                                                                                },
   { "sbyte",                           E_Token::TYPE,             e_LANG_CS                                                                                 },
   { "scope",                           E_Token::D_SCOPE,          e_LANG_D                                                                                  },
   { "sealed",                          E_Token::QUALIFIER,        e_LANG_CS                                                                                 },
   { "section",                         E_Token::PP_SECTION,       e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "self",                            E_Token::THIS,             e_LANG_OC                                                                                 },
   { "set",                             E_Token::GETSET,           e_LANG_CS | e_LANG_VALA                                                                   },
   { "short",                           E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "signal",                          E_Token::ACCESS,           e_LANG_VALA                                                                               },
   { "signals",                         E_Token::ACCESS,           e_LANG_CPP                                                                                },
   { "signed",                          E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "size_t",                          E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "sizeof",                          E_Token::SIZEOF,           e_LANG_C | e_LANG_CPP | e_LANG_CS | e_LANG_VALA | e_LANG_PAWN                             },
   { "sleep",                           E_Token::SIZEOF,           e_LANG_PAWN                                                                               },
   { "stackalloc",                      E_Token::NEW,              e_LANG_CS                                                                                 },
   { "state",                           E_Token::STATE,            e_LANG_PAWN                                                                               },
   { "static",                          E_Token::QUALIFIER,        e_LANG_ALL                                                                                },
   { "static_cast",                     E_Token::TYPE_CAST,        e_LANG_CPP                                                                                },
   { "stock",                           E_Token::STOCK,            e_LANG_PAWN                                                                               },
   { "strictfp",                        E_Token::QUALIFIER,        e_LANG_JAVA                                                                               },
   { "string",                          E_Token::TYPE,             e_LANG_CS | e_LANG_VALA                                                                   },
   { "struct",                          E_Token::STRUCT,           e_LANG_C | e_LANG_CPP | e_LANG_OC | e_LANG_CS | e_LANG_D | e_LANG_VALA                    },
   { "super",                           E_Token::SUPER,            e_LANG_D | e_LANG_JAVA | e_LANG_ECMA                                                      },
   { "switch",                          E_Token::SWITCH,           e_LANG_ALL                                                                                },
   { "synchronized",                    E_Token::QUALIFIER,        e_LANG_D | e_LANG_ECMA                                                                    },
   { "synchronized",                    E_Token::SYNCHRONIZED,     e_LANG_JAVA                                                                               },
   { "tagof",                           E_Token::TAGOF,            e_LANG_PAWN                                                                               },
   { "template",                        E_Token::TEMPLATE,         e_LANG_CPP | e_LANG_D                                                                     },
   { "this",                            E_Token::THIS,             e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_VALA | e_LANG_ECMA               },
   { "throw",                           E_Token::THROW,            e_LANG_CPP | e_LANG_CS | e_LANG_VALA | e_LANG_D | e_LANG_JAVA | e_LANG_ECMA               },
   { "throws",                          E_Token::QUALIFIER,        e_LANG_JAVA | e_LANG_ECMA | e_LANG_VALA                                                   },
   { "transient",                       E_Token::QUALIFIER,        e_LANG_JAVA | e_LANG_ECMA                                                                 },
   { "true",                            E_Token::WORD,             e_LANG_ALL                                                                                },
   { "try",                             E_Token::TRY,              e_LANG_CPP | e_LANG_CS | e_LANG_D | e_LANG_JAVA | e_LANG_ECMA | e_LANG_VALA               },
   { "tryinclude",                      E_Token::PP_INCLUDE,       e_LANG_PAWN | e_FLAG_PP                                                                   },
   { "typedef",                         E_Token::TYPEDEF,          e_LANG_C | e_LANG_CPP | e_LANG_OC | e_LANG_D                                              },
   { "typeid",                          E_Token::SIZEOF,           e_LANG_CPP | e_LANG_D                                                                     },
   { "typename",                        E_Token::TYPENAME,         e_LANG_CPP                                                                                },
   { "typeof",                          E_Token::DECLTYPE,         e_LANG_C | e_LANG_CPP                                                                     },
   { "typeof",                          E_Token::SIZEOF,           e_LANG_CS | e_LANG_D | e_LANG_VALA | e_LANG_ECMA                                          },
   { "ubyte",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "ucent",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "uint",                            E_Token::TYPE,             e_LANG_CS | e_LANG_VALA | e_LANG_D                                                        },
   { "ulong",                           E_Token::TYPE,             e_LANG_CS | e_LANG_VALA | e_LANG_D                                                        },
   { "unchecked",                       E_Token::QUALIFIER,        e_LANG_CS                                                                                 },
   { "undef",                           E_Token::PP_UNDEF,         e_LANG_ALL | e_FLAG_PP                                                                    },
   { "union",                           E_Token::UNION,            e_LANG_C | e_LANG_CPP | e_LANG_D                                                          },
   { "unittest",                        E_Token::UNITTEST,         e_LANG_D                                                                                  },
   { "unowned",                         E_Token::QUALIFIER,        e_LANG_VALA                                                                               },
   { "unsafe",                          E_Token::UNSAFE,           e_LANG_CS                                                                                 },
   { "unsafe_unretained",               E_Token::QUALIFIER,        e_LANG_OC                                                                                 },
   { "unsigned",                        E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "ushort",                          E_Token::TYPE,             e_LANG_CS | e_LANG_VALA | e_LANG_D                                                        },
   { "using",                           E_Token::USING,            e_LANG_CPP | e_LANG_CS | e_LANG_VALA                                                      },
   { "var",                             E_Token::TYPE,             e_LANG_CS | e_LANG_VALA | e_LANG_ECMA                                                     },
   { "version",                         E_Token::D_VERSION,        e_LANG_D                                                                                  },
   { "virtual",                         E_Token::QUALIFIER,        e_LANG_CPP | e_LANG_CS | e_LANG_VALA                                                      },
   { "void",                            E_Token::TYPE,             e_LANG_ALLC                                                                               },
   { "volatile",                        E_Token::QUALIFIER,        e_LANG_C | e_LANG_CPP | e_LANG_CS | e_LANG_JAVA | e_LANG_ECMA                             },
   { "volatile",                        E_Token::VOLATILE,         e_LANG_D                                                                                  },
   { "wchar",                           E_Token::TYPE,             e_LANG_D                                                                                  },
   { "wchar_t",                         E_Token::TYPE,             e_LANG_C | e_LANG_CPP                                                                     },
   { "weak",                            E_Token::QUALIFIER,        e_LANG_VALA                                                                               },
   { "when",                            E_Token::WHEN,             e_LANG_CS                                                                                 },
   { "where",                           E_Token::WHERE,            e_LANG_CS                                                                                 },
   { "while",                           E_Token::WHILE,            e_LANG_ALL                                                                                },
   { "with",                            E_Token::D_WITH,           e_LANG_D | e_LANG_ECMA                                                                    },
   { "xor",                             E_Token::SARITH,           e_LANG_CPP                                                                                },
   { "xor_eq",                          E_Token::SASSIGN,          e_LANG_CPP                                                                                },
};
#endif /* CHUNK_TAG_T_H_INCLUDED */
