name: uncrustify_test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake-part-and-tests
        env:
          BADGE: linux
        run: mkdir build;
          cd build;
          cmake -DCMAKE_BUILD_TYPE=Release ..;
          make;
          ../scripts/run_ctest.py
