name: Windows test
on: [push, pull_request]

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  uncrustify:
    name: ${{ matrix.configuration }} - ${{ matrix.generator }}

    strategy:
      matrix:
        configuration: [Debug, Release]
        generator: ["Visual Studio 18 2026"]

    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DUNCRUSTIFY_SEPARATE_TESTS=ON -G "Visual Studio 18 2026" ..

      - name: Build
        run: |
          cd build
          $cores = (Get-CimInstance Win32_Processor).NumberOfCores
          Write-Output "Detected CPU cores: $cores"
          cmake --build . --config ${{ matrix.configuration }} --parallel $cores

      - name: Run tests
        run: |
          cd build
          $cores = (Get-CimInstance Win32_Processor).NumberOfCores
          Write-Output "Detected CPU cores: $cores"
          $env:PYTHONIOENCODING = "utf-8"
          $env:UNCRUSTIFY_TEST_JOBS = $cores
          python ../scripts/run_ctest.py -- -j $cores -C ${{ matrix.configuration }}
